version: '2'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 8000:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./www:/var/www/html
        depends_on:
            - php
            - mysql
        restart: always

    php:
        image: php:7-fpm-alpine
        container_name: php-7.1.11
        volumes:
            - ./www:/var/www/html
        restart: always
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin 
        container_name: phpmyadmin
        ports: 
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        depends_on:
            - mysql
        restart: always

    mysql:
        image: mysql
        container_name: mysql
        ports:
            - 3307:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=database
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        restart: always